import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AppGen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} h-screen overflow-hidden`}>
        <Providers>{children}</Providers>
        <Script src='../../node_modules/flowbite/dist/flowbite.js' />
      </body>
    </html>
  )
}
